{
 "title": "API Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Calculator Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "errors_calculator_total{}", "legendFormat": "{{endpoint}}" }
   ]
  },
  {
   "title": "HTTP average duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(http_requests_total{job=\"api\"}[5m])",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "HTTP requests per route",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(http_requests_total{endpoint=\"/fibo\",method=\"get\"}[5m])",
     "legendFormat": "fibo"
    },
    {
     "expr": "rate(http_requests_total{endpoint=\"/sum1n\",method=\"get\"}[5m])",
     "legendFormat": "sum1n"
    },
    {
     "expr": "rate(http_requests_total{endpoint=\"/calculator\",method=\"post\"}[5m])",
     "legendFormat": "calculator"
    },
    { "expr": "rate(list_size{}[5m])", "legendFormat": "size" }
   ]
  },
  {
   "title": "Last Values",
   "type": "stat",
   "gridPos": { "h": 11, "w": 11, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "last_calculator{}", "legendFormat": "calculator" },
    { "expr": "last_fibo{}", "legendFormat": "fibo" },
    { "expr": "last_sum1n{}", "legendFormat": "sum1n" },
    { "expr": "list_size{}", "legendFormat": "Size" }
   ]
  }
 ]
}